import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import House from './components/House'

export default function Home() {
  const [characters, setCharacters] = useState([])
  const [houses, setHouses] = useState(null)

  useEffect(() => {
    getData()
  }, [])

  const getData = async () => {
    const res = await fetch(`http://hp-api.herokuapp.com/api/characters/students`)
    const data = await res.json()
    setCharacters(data)
    console.log(data)
  }

  const handleClick = ({ e, team }) => {
    let filteredHouse = characters.filter(club => club.house === team)
    let chooseHouse = e.target.value
    chooseHouse !== "Gryffindor"
      ? setHouses(filteredHouse(chooseHouse))
      : setHouses(characters.house)
      console.log(characters.house);
  }

  const people = characters.map(character => (
    <div className="my-8 py-8 pl-6 bg-[url('/parchment.png')]" key={character.id}>
      <h1 className='mb-4 text-xl'><strong>{character.name}</strong></h1>
      <Image
        className='rounded-lg'
        src={character.image || '/default.jpg'}
        alt={character.name}
        height={250}
        width={250}
      />
      <h2>House: <strong>{character.house}</strong></h2>
      <h3>State: <strong>{character.alive === true ? "Alive" : "Dead"}</strong></h3>
      <p>Ancestry: {character.ancestry || "Unknown"}</p>
      <p>Gender: {character.gender}</p>      
      <p>{character.gender === "male" ? "Actor: " : "Actress: "} 
        <strong>
          {character.actor || "Unknown"}
        </strong>
      </p>
    </div>
  ))

  return (
    <div className="app px-8 w-full h-full">
      <Head>
        <title>Harry Potter 🧙</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-center'>
        <header className='flex justify-center items-center p-6'>
          <Image src={'/title.png'} alt='title' height={150} width={300} />
        </header>
        <form>
          <House onClick={handleClick} house="Gryffindor" />
          <House onClick={handleClick} house="Slytherin" />
          <House onClick={handleClick} house="Hufflepuff" />
          <House onClick={handleClick} house="Ravenclaw" />
            
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 text-center'>
            {people}
          </div>
        </form>
      </main>

      <footer className="flex flex-1 py-8 border-t-2 border-gray-800 justify-center items-center">
        <a
          className='flex justify-center items-center grow'
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {' '}
          <span className="h-1 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
